db: fix missing fields in SEARCH query
Criteria filters on fields such as the subject, internal date, and
so on. If the CTE doesn't fetch these fields the query fails with
errors such as:

    ERROR: column "subject" does not exist (SQLSTATE 42703)